CREATE TABLE Owner
(id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
surname VARCHAR(75) NOT NULL,
lastname VARCHAR(100) NULL,
phone VARCHAR(16) NOT NULL,
mail VARCHAR(200) NULL,
PRIMARY KEY (id),
INDEX ind_mail (mail(200)));

CREATE TABLE Guard
(id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
surname VARCHAR(75) NOT NULL,
lastname VARCHAR(100) NULL,
phone VARCHAR(16) NOT NULL,
mail VARCHAR(200) NULL,
exp_year INT NOT NULL,
PRIMARY KEY (id),
INDEX ind_mail (mail(200)));

CREATE TABLE Auto
(id INT NOT NULL AUTO_INCREMENT,
owner_id int NOT NULL,
model VARCHAR(100) NOT NULL,
color VARCHAR(50) NOT NULL,
PRIMARY KEY (id));

CREATE TABLE Model
(model VARCHAR(100) NOT NULL,
mark VARCHAR(100) NOT NULL,
PRIMARY KEY (model(100)));


CREATE TABLE Mark
(mark VARCHAR(100) NOT NULL,
PRIMARY KEY (mark(100)));

CREATE TABLE Records
(id int NOT NULL,
auto_id int NOT NULL,
guard_id int NOT NULL,
date_arrived DATE NULL,
date_leaving DATE NULL,
PRIMARY KEY (id)
);


ALTER TABLE Model ADD CONSTRAINT model_mark FOREIGN KEY (mark) REFERENCES Mark(mark) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Auto ADD CONSTRAINT auto_model FOREIGN KEY (model) REFERENCES Model(model) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Auto ADD CONSTRAINT auto_owner FOREIGN KEY (owner_id) REFERENCES Owner(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Records ADD CONSTRAINT record_auto FOREIGN KEY (auto_id) REFERENCES Auto(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Records ADD CONSTRAINT record_guard FOREIGN KEY (guard_id) REFERENCES Guard(id) ON DELETE CASCADE ON UPDATE CASCADE;
